del *.obj 
del cmtk.exe
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c cm_init.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c main.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c NetHelper.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c IniHelper.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c getopt.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c -GX cm_function.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c cm_init_dev.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c cm_init_task.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c cm_thread.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c cm_utils.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c cm_result.cpp
cl  /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE /I D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/INCLUDE/STLPORT   /MD /GR /c -GX cmtkp.cpp
link *.obj ice.lib iceutil.lib   /RELEASE /LIBPATH:D:/DEVELOP/COMPONENTS/ICE-3.3.1-VC60/LIB /IMPLIB:ice /IMPLIB:iceutil /nologo  /OUT:cmtk.exe
del *.obj
